/// Flutter icons MIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MIcons
///      fonts:
///       - asset: fonts/MIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MIcons {
  MIcons._();

  static const _kFontFam = 'MIcons';

  static const IconData settings =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: null);
  static const IconData book =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: null);
  static const IconData note =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: null);
  static const IconData home =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: null);
}
